### PR TITLE
Able to parse the output with bentoml py3.6

### PR DESCRIPTION
**Pull request by samuelmaina**
Hi @GemmaTuron ,
I was finally able to predict with the standard requirement. The problem was that the main.py should write the results as json instead of .csv file. The last commit to main.py was to convert the results in json https://github.com/ersilia-os/eos5qfo/commit/49ebcd9e0c4ccb08d85f48282f20c53dfc91030d

### CODE REVIEW

**Comment by samuelmaina** [comment]
The model is fetching successfully in the workflows. I was also able fetch and run locally.  
[eos5qfo_cli_pred.csv](https://github.com/ersilia-os/eos5qfo/files/12320150/eos5qfo_cli_pred.csv)
[eos5qfo_cli_fetch (1).log](https://github.com/ersilia-os/eos5qfo/files/12320151/eos5qfo_cli_fetch.1.log)

```
09:13:43 | DEBUG    | Schema not yet available
09:13:43 | DEBUG    | Done with unique posting
09:13:43 | DEBUG    | Metadata needs to be calculated
09:13:43 | DEBUG    | [{'input': {'key': 'f714e0b82911ab6ae92add25326be299', 'input': ['CC1C2C(CC3(C=CC(=O)C(=C3C2OC1=O)C)C)O', 'C1=CN=CC=C1C(=O)NN'], 'text': 'CC1C2C(CC3(C=CC(=O)C(=C3C2OC1=O)C)C)O.C1=CN=CC=C1C(=O)NN'}, 'output': {'products': ['CC1=C2C3OC(=O)C(C)C3C(O)CC2(C)C=CC1=NNC(=O)c1ccncc1', 'O']}}, {'input': {'key': '4497e531f523ced31965305c4f0929bc', 'input': ['CC(=O)OC1=CC=CC=C1C(=O)O', 'CC(C)CC1=CC=C(C=C1)C(C)C(=O)O', 'CC1(OC2C(OC(C2O1)(C#N)C3=CC=C4N3N=CN=C4N)CO)C'], 'text': 'CC(=O)OC1=CC=CC=C1C(=O)O.CC(C)CC1=CC=C(C=C1)C(C)C(=O)O.CC1(OC2C(OC(C2O1)(C#N)C3=CC=C4N3N=CN=C4N)CO)C'}, 'output': {'products': ['CC(=O)Oc1ccccc1C(=O)O', 'CC(C)Cc1ccc(C(C)C(=O)O)cc1', 'CC1(C)OC2CCOC(C#N)(c3ccc4c(N)ncnn34)C2O1', 'O']}}]
09:13:43 | ERROR    | Input data types are not consistent
09:13:43 | ERROR    | Output data types are not consistent
09:13:43 | DEBUG    | Latest meta: {'products': None}
09:13:43 | DEBUG    | Schema: {'input': {'key': {'type': 'string'}, 'text': {'type': 'string'}}, 'output': {}}
09:13:43 | DEBUG    | {'input': {'key': {'type': 'string'}, 'text': {'type': 'string'}}, 'output': {}}
09:13:43 | DEBUG    | API schema saved at /home/runner/eos/dest/eos5qfo/api_schema.json
09:13:44 | DEBUG    | Fetching eos5qfo done in time: 0:02:28.045431s
09:13:44 | INFO     | Fetching eos5qfo done successfully: 0:02:28.045431
[]
👍 Model eos5qfo fetched successfully!
```
I guess that there is a problem with the test data passed to ersilia in the workflow since the workflow is failing due to input being Null.
```
Traceback (most recent call last):
  File "/usr/share/miniconda/bin/ersilia", line 8, in <module>
    sys.exit(cli())
  File "/usr/share/miniconda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/share/miniconda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/share/miniconda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/share/miniconda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/share/miniconda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/cli/commands/__init__.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/cli/commands/api.py", line 41, in api
    for result in mdl.api(
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/core/model.py", line 195, in _api_runner_iter
    for result in api.post(input=input, output=output, batch_size=batch_size):
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/serve/api.py", line 317, in post
    unique_input, mapping = self._unique_input(input)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/serve/api.py", line 279, in _unique_input
    for i, inp in enumerate(self.input_adapter.adapt_one_by_one(input)):
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/io/input.py", line 172, in adapt_one_by_one
    data = self.adapter.adapt(inp)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/io/input.py", line 144, in adapt
    data = self._adapt(inp)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/io/input.py", line 138, in _adapt
    return self._file_reader(inp)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/io/input.py", line 130, in _file_reader
    reader = TabularFileReader(path=inp, IO=self.IO)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/io/readers/file.py", line 544, in __init__
    self._standardize()
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/io/readers/file.py", line 548, in _standardize
    tfss = TabularFileShapeStandardizer(
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/io/readers/file.py", line 384, in __init__
    self.read_input_columns()
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/io/readers/file.py", line 295, in read_input_columns
    assert input is not None
AssertionError
Error: Process completed with exit code 1.
```

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 
Could it be the input type we are passing is a Pair of Lists, not a List? isn't that the correct format, and then the example is not being prepared right?

**Comment by samuelmaina** [comment]
> Hi @samuelmaina Could it be the input type we are passing is a Pair of Lists, not a List? isn't that the correct format, and then the example is not being prepared right?

Yeah  @GemmaTuron . That is the problem. The workflow is generating  5 smiles which are are 1D (1 smile per row)  but the  the required input is a list of smilies(smiles separated by . for .csv files). I guess the workflows need to be changed to adopt to the input shape

**Comment by samuelmaina** [comment]
Hello @GemmaTuron ,
The I run the `ersilia  sample` command  locally and the input.csv file produced did not have any rows in it and calling 'run' on it threw the `input is None` which is the same error in the workflow.  I then fetched a model with a single shape input and run the `ersilia  sample` command again and the input csv had the specified number of rows with valid keys and smiles. 
The `sample`  command is reading the model shape but it seems it can't not handle a  List input.
The sample command is reading from  a list of  maintained  files  as can be seen from  https://github.com/ersilia-os/ersilia/blob/master/ersilia/cli/commands/sample.py  and https://github.com/ersilia-os/ersilia/blob/master/ersilia/db/hubdata/samplers.py . The reason why only single are working it is because https://github.com/ersilia-os/ersilia-model-hub-maintained-inputs/blob/main/compound/single/inp-000.csv is the only file that  is present in the ersilia-model-hub-maintained-inputs. The solution to this is to create a .csv file in the ersilia-model-hub-maintained-inputs/compound folder that has . separated smiles to represent list input.
```
    def _get_inputs_from_maintained_file(self):
        file_name = "inp-000.csv"  #  TODO extend
        assert len(self.input_type) == 1
        input_type = self.input_type[0].lower()
        input_shape = self.input_shape.lower().replace(" ", "-")
        url = (
            "https://raw.githubusercontent.com/ersilia-os/{0}/main/{1}/{2}/{3}".format(
                _ERSILIA_MAINTAINED_INPUTS_GITHUB_REPOSITORY,
                input_type,
                input_shape,
                file_name,
            )
        )
        with requests.Session() as s:
            download = s.get(url)
            decoded_content = download.content.decode("utf-8")
            cr = csv.reader(decoded_content.splitlines(), delimiter=",")
            data = list(cr)[1:]
            R = []
            for r in data:
                R += [r]
        return R

    def sample(self, n_samples, file_name):
        entities = self._get_inputs_from_maintained_file()
        entities = random.sample(entities, min(n_samples, len(entities)))
        if file_name is None:
            for e in entities:
                print(e[1])  # TODO Change print to click?
        else:
            with open(file_name, "w") as f:
                writer = csv.writer(f)
                writer.writerow(["key", "input"])
                for r in entities:
                    writer.writerow(r)
```
I have made two PR , one to modify the sampling url in ersilia (https://github.com/ersilia-os/ersilia/pull/774) and the other to add the samples (https://github.com/ersilia-os/ersilia-model-hub-maintained-inputs/pull/1)

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

Thanks, the sample command is indeed not complete yet, I'll have a look at your suggestion!

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

I am checking your PRs but meanwhile can you show me what you are using as input? Because as I understand the model requires as input the reactants, so, a pair of lists, but you are passing single molecules?

**Comment by samuelmaina** [comment]
> Hi @samuelmaina
> 
> I am checking your PRs but meanwhile can you show me what you are using as input? Because as I understand the model requires as input the reactants, so, a pair of lists, but you are passing single molecules?

 Hi @GemmaTuron , I am reading  r[0] in input rows in the main.py with the `smiles` column having many smiles separated by .  in the input csv.This is working with run.sh. I looked at the input section of the docs and it is suggesting we do that.
I guess we only read r as a whole in the input rows when the input is a pair of lists or list of lists.

**Comment by GemmaTuron** [comment]
On a second thought, the input as list is fine!
Can you copy the input you have been using here so we can check and see if it's the best format?

**Comment by samuelmaina** [comment]
Here is the sample that I am running  with run.sh [input.csv](https://github.com/ersilia-os/eos5qfo/files/12361351/input.csv)

**Comment by GemmaTuron** [comment]
Thanks @samuelmaina !
If a user is passing only one list as input, what happens if it is a single .csv file with one column? how is this processed? See list of molecules in the[ documentation](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/inputs)
Maybe we should add a function that discriminates if the input is a single list or several

**Comment by samuelmaina** [comment]
> Thanks @samuelmaina ! If a user is passing only one list as input, what happens if it is a single .csv file with one column? how is this processed? See list of molecules in the[ documentation](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/inputs) Maybe we should add a function that discriminates if the input is a single list or several

For now we are assuming that the input is a single column hence a single column with dot separated smiles will work.The r[0] will contain a string with the smiles separated with a dot since the reader does not parse this to a list. This model process the  string into a list and If the input is a single column without dot separated smiles the code will throw an error. This works for this model but I guess other models the string would be not split.
For now the model fails when passed a list of comma separated smiles in the .csv which is not ideal. 
I will modify the code to to parse the smiles models into a list if passed a single column dot-separated smiles or a comma-separated smiles.

**Comment by samuelmaina** [comment]
> > Thanks @samuelmaina ! If a user is passing only one list as input, what happens if it is a single .csv file with one column? how is this processed? See list of molecules in the[ documentation](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/inputs) Maybe we should add a function that discriminates if the input is a single list or several
> 
> For now we are assuming that the input is a single column hence a single column with dot separated smiles will work.The r[0] will contain a string with the smiles separated with a dot since the reader does not parse this to a list. This model process the string into a list and If the input is a single column without dot separated smiles the code will throw an error. This works for this model but I guess other models the string would be not split. For now the model fails when passed a list of comma separated smiles in the .csv which is not ideal. I will modify the code to to parse the smiles models into a list if passed a single column dot-separated smiles or a comma-separated smiles.


@GemmaTuron , I think  I should just accept a comma separated csv file for this model and just leave the  dot-separated smiles for the pair of list and list of list cases.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

According to the file you shared, there are several lists in a single column. Each list is in a ROW, with smiles separated by dots - this is the correct format to pass several lists together, otherwise we won't be able to pass several inputs (lists) in one file
What I am asking is if the user passes a single list, let's say, 10 smiles, instead of in one row separated by dots, in one single column where each smiles is one row - that is a possibility if they want to pass a single input

**Comment by samuelmaina** [comment]
> Hi @samuelmaina
> 
> According to the file you shared, there are several lists in a single column. Each list is in a ROW, with smiles separated by dots - this is the correct format to pass several lists together, otherwise we won't be able to pass several inputs (lists) in one file What I am asking is if the user passes a single list, let's say, 10 smiles, instead of in one row separated by dots, in one single column where each smiles is one row - that is a possibility if they want to pass a single input

Hi @GemmaTuron ,
The code return the same smiles per row.The input and the output are identical in this case. Should I throw an error if this is the case?

**Comment by GemmaTuron** [comment]
Could we actually add a check to see if that is the case and then convert the input to the correct format?
IF a single list of smiles is passes, in one column, convert to a list dot separated

**Comment by samuelmaina** [comment]
> Could we actually add a check to see if that is the case and then convert the input to the correct format? IF a single list of smiles is passes, in one column, convert to a list dot separated

Okay I will do this.

**Comment by samuelmaina** [comment]
Hi @GemmaTuron ,
The input is being serialized by ersilia as can be seen by this input and output.
[out.csv](https://github.com/ersilia-os/eos5qfo/files/12393970/out.csv)
[output.csv](https://github.com/ersilia-os/eos5qfo/files/12393971/output.csv)

**Pull request merged**
